### ISSUE TITLE
split_nm function error?

### ISSUE THREAD

**Issue by PeterMcGor** [amarquand/nispat#12]
Dear authors;

Firstly, let me thank you for the code and sharing!

I have been employing your code in the last days (basically just wrapping it in a docker) and I think there is a small mistake in the code. 

The function `split_nm` inside `normative_parallel.py`  shows the following at line 289:

```python
respfile = pd.read_pickle(testrespfile_path)
```
but I guess it should be: 
```python
testrespfile = pd.read_pickle(testrespfile_path)
```
Otherwise, respfile and testrespfile are the same at the binary case, right? 

Best!

**Comment by smkia** [comment]
Hi Peter,

Thanks for your interest in nispat,
You are right, we are aware of this bug and had resolved it in the development branch (see https://github.com/amarquand/nispat/commit/c8682d6171450b1cb4748fc5153c70e69dc02f06).
We will merge the development branch with the master branch soon and after some extra tests. 

Cheers!

**Comment by PeterMcGor** [comment]
Thanks to you! 

Eager to see the new version!
