### ISSUE TITLE
pip install nispat or conda install nispat not working

### ISSUE THREAD

**Issue by maartenmennes** [amarquand/nispat#13]
Hello,

it appears that the pip/conda install route as suggested in the how_to_install document do not work for nispat?

**Comment by maartenmennes** [comment]
Hi Thomas,
Thanks! I just saw the how_to_install.txt in your fork of nispat. That one is more clear I think, and worked :-)
Is the plan to push this to this (andre's) one? I also see you have a more recent version of fileio.py?

**Comment by RindKind** [comment]
Yes of course. I just don’t find the time at moment. The version on my
github is for practicals etc and will not be further developed. I should
give it a different name. Best wishes. Thomas

Am Dienstag, 10. September 2019 schrieb Maarten Mennes <
notifications@github.com>:

**Comment by maartenmennes** [comment]
Hi Thomas,
thanks! I've improved things a bit an put them in via this pull request #14
