### ISSUE TITLE
NIfTI concatenation

### ISSUE THREAD

**Issue by asadmalik85** [amarquand/nispat#15]
Hi,

I have a very basic question and sorry if I've missed something very obvious:

If the response variables are in a NIfTI file, how is the multi-subject NIfTI created? Is a 4-D NIfTI used, where the time dimension indexes subjects?

Thanks,
Asad

**Comment by RindKind** [comment]
Yes, dependent what you are doing it works this way.

Am Mi., 11. Sept. 2019 um 13:42 Uhr schrieb Asad Malik <
notifications@github.com>:

**Comment by asadmalik85** [comment]
Thanks Thomas.

Could you elaborate a bit on what you mean by dependent on what I am doing - does the NIfTI structure vary in how subjects are combined based on input parameters?

Thanks,
Asad
