### ISSUE TITLE
Numerical issue and bug

### ISSUE THREAD

**Issue by nidaye1999** [amarquand/nispat#18]
Function "squared_dist" in "utils.py" will cause some numerical issue when x and z are large but the difference is small. I used function "distance_matrix" from scipy instead.

Line 209 in "normative.py" should be:
nz = np.where(np.bitwise_and(np.isfinite(Y).**_all_**(axis=0),np.var(Y, axis=0) != 0))[0]

**Comment by amarquand** [comment]
Thanks for letting us know! We'll look to address this in the next version.
