### ISSUE TITLE
-c arg unable to read .mat file created by CONN

### ISSUE THREAD

**Issue by onimonipea** [amarquand/nispat#20]
I am attempting to create a normative model from MRI data which I have preprocessed in CONN. Although I have generated .nii files to use for <infile>, CONN does not seem to generate a file to use as <covariates>. When I attempt to pass a .mat file I receive the "I don't know what to do with + filename" error. 

How do I create a covariates file for my preprocessed data to create a normative model? 

Thank you

**Comment by amarquand** [comment]
Basically, you need to create a text file of size N x p where p is the number of covariates and N is the sample size. Each row contains the covariates for a single subject
