### ISSUE TITLE
Instalation instructions 

### ISSUE THREAD

**Issue by Sabryr** [amarquand/nispat#24]
1. There is a disparity between what the README.md says and what the requirements.txt file in the achieve download (https://github.com/amarquand/nispat/archive/v1.2.2.tar.gz). e,g,   requirements.txt indicated tensorflow==0.12.1 as an requirement. 
is  tensorflow==0.12.1 a runtime requirement or not a requirement ?
2. If it is a requirement then it is too old to be installed with pip
pip install tensorflow==0.12.1
ERROR: Could not find a version that satisfies the requirement tensorflow==0.12.1 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2)
ERROR: No matching distribution found for tensorflow==0.12.1

**Comment by RindKind** [comment]
1. This is not a runtime requirement and it will be changed in the
appropriate file. Thank you for pointing it out.
2. You can use an up-to-date version of TensorFlow, it will be changed to
avoid confusion. Thank you for pointing it out.

Am Fr., 10. Apr. 2020 um 22:36 Uhr schrieb Sabry Razick <
notifications@github.com>:

**Comment by Sabryr** [comment]
Thank you,
If tensorflow is needed I have to set it up in an entirely different way than if you do not need it. So the question is whether I should include it at all ?

**Comment by RindKind** [comment]
Hi.

There is no requirement for tensorflow -at least for the basic functions-
Don't worry about it. Have a good weekend.

Thomas

**Comment by amarquand** [comment]
pull request merged
